markdown: Pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib

kramdown:
  input: GFM
baseurl: http://vertexoperator.github.io/
exclude: ['src']
gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-pandoc
