markdown: kramdown
kramdown:
  input: GFM
baseurl: http://vertexoperator.github.io/
exclude: ['src']
gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed

